#!/bin/bash
typeprompt=$(GDK_BACKEND=x11 yad --class=womic --title="WO Mic Client" --form --field=":CB" --text="Select Connection Type" --width=300 --height=120 Bluetooth\!Wi-Fi --num-output --field="Load aloop module (requires sudo):CHK" 1 --bool-fmt=1)
type=${typeprompt::1} #1:Bluetooth,2:Wi-FI
loadaloop=${typeprompt:2:(-1)}

if [[ $type -eq 1 ]]; then
	listdevices=$(bluetoothctl devices)
	macs=()
	names=()
	m=0
	d=-1
	for x in $listdevices; do
		if [[ $x == "Device" ]]; then
			((d++))
			m=1
		else
			if [[ $m -eq 1 ]]; then
				m=0
				macs+=("$x")
			else
				names[d]+="$x "
			fi
		fi
	done
	formatted=$(IFS=! ; echo "${names[*]}")
	prompt=$(GDK_BACKEND=x11 yad --title="WO Mic Client" --class="womic" --form --field=":CB" "$formatted" --text="Select Device"  --num-output --field="Load aloop module (requires sudo):CHK" "$loadaloop" --bool-fmt=1)
	macindex=$((${prompt::1}-1))
	loadaloop=${prompt:2:(-1)}
	if [[ $loadaloop -eq 1 ]]; then
		pkexec modprobe snd-aloop
	fi
	mac=${macs[$macindex]}
	connect=$(micclient -t Bluetooth "$mac") &

elif [[ $type -eq 2 ]]; then
	sampleip=$(hostname -I)
	prompt=$(GDK_BACKEND=x11 yad --title="WO Mic Client" --class="womic" --form --field="" "$sampleip" --text="Enter device IP" --field="Load aloop module (requires sudo):CHK" "$loadaloop" --bool-fmt=1)
	ip=${prompt:0:(-3)}
	loadaloop=${prompt:(-2):(-1)}
	if [[ $loadaloop -eq 1 ]]; then
		pkexec modprobe snd-aloop
	fi
	connect=$(micclient -t WIFI "$ip") &
fi
