#!/bin/bash
typeprompt=$(GDK_BACKEND=x11 yad --class=womic --form --field=":CB" --text="Select Connection Type" --width=300 --height=120 Bluetooth\!Wi-Fi --field="Load aloop module (requires sudo):CHK" TRUE --title="WO Mic Client")
type=${typeprompt%%|*}
loadaloop=${typeprompt#$type*}
loadaloop=${loadaloop:1:(-1)}


if [[ $type == "Bluetooth" ]]; then
	devicescommand=$(bluetoothctl devices)
	macs=()
	devicenames=()
	isnextmac=0
	devicestring=""
	firstiteration=1
	for x in $devicescommand; do
		if [[ $x == "Device" ]]; then
			if [[ $firstiteration -eq 1 ]]; then
				firstiteration=0
			else
				devicestring=${devicestring:0:(-1)}
				devicenames+=( "$devicestring" )
				devicestring=""
			fi
			isnextmac=1
		else
			if [[ $isnextmac -eq 1 ]]; then
				isnextmac=0
				macs+=( "$x" )
			else
				devicestring+="$x "
			fi
		fi
	done
	devicestring=${devicestring:0:(-1)}
	devicenames+=( "$devicestring" )
	devicestring=$(IFS=! ; echo "${devicenames[*]}")
	deviceprompt=$(GDK_BACKEND=x11 yad --title="WO Mic Client" --class="womic" --form --field=":CB" "$devicestring" --text="Select Device"  --num-output --field="Load aloop module (requires sudo):CHK" "$loadaloop")
	device=${deviceprompt%%|*}
	loadaloop=${deviceprompt#$device*}
	loadaloop=${loadaloop:1:(-1)}
	if [[ $loadaloop == "TRUE" ]]; then
		pkexec modprobe snd-aloop
	fi
	macindex=$device-1
	device=${macs[$macindex]}
	connect=$(micclient -t Bluetooth "$device") &
elif [[ $type == "Wi-Fi" ]]; then
	ipaddress=$(hostname -I)
	deviceprompt=$(GDK_BACKEND=x11 yad --title="WO Mic Client" --class="womic" --form --field="" "$ipaddress" --text="Enter device IP" --field="Load aloop module (requires sudo):CHK" "$loadaloop")
	device=${deviceprompt%%|*}
	loadaloop=${deviceprompt#$device*}
	loadaloop=${loadaloop:1:(-1)}
	if [[ $loadaloop == "TRUE" ]]; then
		pkexec modprobe snd-aloop
	fi
	connect=$(micclient -t WIFI "$device") &
fi
